import moment from 'moment'
export const inboundIndexes = [
    {
        fieldName:'applyCount',
        title:'入库申请',
        value:0,
        router:'inboundApplyList',
        params:{
            businessTime:[moment().startOf('day'),moment().endOf('day')],
            state:0
        }
    },
    {
        fieldName:'asnCount',
        title:'预约入库',
        value:0,
    },
    {
        fieldName:'instockCount',
        title:'已入库',
        value:0,
        router:'inboundOrderList',
        params:{
            inboundDate:[moment().startOf('day'),moment().endOf('day')],
            state:4
        }
    }
]
export const putawayIndexes = [
    {
        fieldName:'toPutCount',
        title:'未上架',
        value:0,
        router:'putawayOrderList',
        params:{
            createTime:[moment().startOf('day'),moment().endOf('day')],
            state:0
        }
    },
    {
        fieldName:'hasPutCount',
        title:'已上架',
        value:0,
        router:'putawayOrderList',
        params:{
            createTime:[moment().startOf('day'),moment().endOf('day')],
            state:2
        }
    }
]

export const outboundIndexes = [
    {
        fieldName:'outCount',
        title:'出库单',
        value:0,
        total:true,
        router:'outboundOrderList',
        params:{
            orderCreateTime:[moment().startOf('day'),moment().endOf('day')],
        }
    },
    {
        fieldName:'undistributedCount',
        title:'未分配',
        value:0,
        router:'outboundOrderList',
        params:{
            orderCreateTime:[moment().startOf('day'),moment().endOf('day')],
            state:0
        }
    },
    {
        fieldName:'forPickingCount',
        title:'待拣货',
        value:0,
        router:'outboundOrderList',
        params:{
            orderCreateTime:[moment().startOf('day'),moment().endOf('day')],
            state:1
        }
    },
    {
        fieldName:'isPickingCount',
        title:'拣货中',
        value:0,
        router:'outboundOrderList',
        params:{
            orderCreateTime:[moment().startOf('day'),moment().endOf('day')],
            state:2
        }
    },
    {
        fieldName:'hasPickingCount',
        title:'已拣货',
        value:0,
        router:'outboundOrderList',
        params:{
            orderCreateTime:[moment().startOf('day'),moment().endOf('day')],
            state:3
        }
    },
    {
        fieldName:'haveOutboundCount',
        title:'已出库',
        value:0,
        router:'outboundOrderList',
        params:{
            orderCreateTime:[moment().startOf('day'),moment().endOf('day')],
            state:4
        }
    }
]
