const linkData = [
    {
        title:'产品',
        childLink:[
            {
                title:'WMS仓储管理系统',
                path:''
            },
            {
                title:'RF移动仓储管理系统',
                path:''
            },
            {
                title:'用户使用协议',
                path:'',
                components:true
            }
        ]
    },
    {
        title:'帮助',
        childLink:[
            {
                title:'快速上手',
                path:''
            },
            {
                title:'视频培训',
                path:''
            }
        ]
    },
    {
        title:'关于我们',
        childLink:[
            {
                title:'公司介绍',
                path:''
            },
            {
                title:'加入我们',
                path:''
            },
            {
                title:'行业方案',
                path:''
            }
        ]
    },
    {
        title:'友情链接',
        childLink:[
            {
                title:'腾讯云',
                path:'https://cloud.tencent.com/'
            },
            {
                title:'富勒科技',
                path:''
            },
            {
                title:'物流指闻',
                path:''
            }
        ]
    },
    {
        title:'联系方式',
        childLink:[
            {
                title:'15102161151',
                path:''
            },
            {
                title:'周一至周日09:00~21:00',
                path:''
            },
            {
                title:'xuchunniu@yijiupi.com',
                path:'xuchunniu@yijiupi.com'
            }
        ]
    }
]

export default linkData